//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptimizeTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptimizeTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
        ///&quot;Win32PrioritySeparation&quot;=dword:00000016.
        /// </summary>
        internal static string _16hexsmooth {
            get {
                return ResourceManager.GetString("_16hexsmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
        ///&quot;Win32PrioritySeparation&quot;=dword:00000025.
        /// </summary>
        internal static string _25hexbalance {
            get {
                return ResourceManager.GetString("_25hexbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
        ///&quot;Win32PrioritySeparation&quot;=dword:00000026.
        /// </summary>
        internal static string _26hexdefault {
            get {
                return ResourceManager.GetString("_26hexdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl]
        ///&quot;Win32PrioritySeparation&quot;=dword:00000028.
        /// </summary>
        internal static string _28hexlowest {
            get {
                return ResourceManager.GetString("_28hexlowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications]
        ///&quot;GlobalUserDisabled&quot;=dword:00000001
        ///
        ///[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]
        ///&quot;BackgroundAppGlobalToggle&quot;=dword:00000000.
        /// </summary>
        internal static string disablebackgroungapps {
            get {
                return ResourceManager.GetString("disablebackgroungapps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///; Registry File By Adamx
        ///; Disable Connected User Experiences and Telemetry
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\DiagTrack]
        ///&quot;Start&quot;=dword:00000004
        ///
        ///; Disable dmwappushservice
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dmwappushservice]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disablediagteleserv {
            get {
                return ResourceManager.GetString("disablediagteleserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_CURRENT_USER\System\GameConfigStore]
        ///&quot;GameDVR_Enabled&quot;=dword:00000000
        ///&quot;GameDVR_FSEBehaviorMode&quot;=dword:00000002
        ///&quot;GameDVR_HonorUserFSEBehaviorMode&quot;=dword:00000000
        ///&quot;GameDVR_DXGIHonorFSEWindowsCompatible&quot;=dword:00000000
        ///&quot;GameDVR_EFSEFeatureFlags&quot;=dword:00000000
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disablefullscreenopt {
            get {
                return ResourceManager.GetString("disablefullscreenopt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\ApplicationManagement\AllowGameDVR]
        ///&quot;value&quot;=dword:00000000
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameDVR]
        ///&quot;AllowGameDVR&quot;=dword:00000000
        ///
        ///[HKEY_CURRENT_USER\Software\Microsoft\Windows\Cu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disablegamebar {
            get {
                return ResourceManager.GetString("disablegamebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; created by Walter Glenn
        ///; for How-To Geek
        ///; article: https://www.howtogeek.com/225844/how-to-make-windows-photo-viewer-your-default-image-viewer-on-windows-10/
        ///
        ///[-HKEY_CLASSES_ROOT\Applications\photoviewer.dll]
        ///
        ///.
        /// </summary>
        internal static string disablephotoviewer {
            get {
                return ResourceManager.GetString("disablephotoviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters]
        ///&quot;EnablePrefetcher&quot;=dword:00000000
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters]
        ///&quot;EnableSuperfetch&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disableprefetch {
            get {
                return ResourceManager.GetString("disableprefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///; Disable Windows Defender Features
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
        ///&quot;DisableAntiSpyware&quot;=dword:00000001
        ///&quot;DisableRoutinelyTakingAction&quot;=dword:00000001
        ///&quot;ServiceKeepAlive&quot;=dword:00000000
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disablewinsec {
            get {
                return ResourceManager.GetString("disablewinsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; created by Walter Glenn
        ///; for How-To Geek
        ///; article: https://www.howtogeek.com/225844/how-to-make-windows-photo-viewer-your-default-image-viewer-on-windows-10/
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll]
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell]
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell\open]
        ///&quot;MuiVerb&quot;=&quot;@photoviewer.dll,-3043&quot;
        ///
        ///[HKEY_CLASSES_ROOT\Applications\photoviewer.dll\shell\open\command]
        ///@=hex(2):25,00,53,00,79,00, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enablephotoviewer {
            get {
                return ResourceManager.GetString("enablephotoviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDefend]
        ///&quot;Start&quot;=dword:00000002
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SecurityHealthService]
        ///&quot;Start&quot;=dword:00000003
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WdNisSvc]
        ///&quot;Start&quot;=dw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enablewinsec {
            get {
                return ResourceManager.GetString("enablewinsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_support_80 {
            get {
                object obj = ResourceManager.GetObject("icons8_support_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00                                                                                                                                                             Registry File By Adamx (youtube.com/AdamxYT)
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile]
        ///&quot;SystemResponsiveness&quot;=dword:00000000
        ///&quot;NetworkThrottlingIndex&quot;=dword:ffffffff
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mmcsstweaks {
            get {
                return ResourceManager.GetString("mmcsstweaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; Created by: Shawn Brink
        ///; Created on: January 28th 2015
        ///; Updated on: June 18th 2017
        ///; Tutorial: https://www.tenforums.com/tutorials/3841-add-take-ownership-context-menu-windows-10-a.html
        ///
        ///
        ///; To remove old Take Ownership context menu
        ///[-HKEY_CLASSES_ROOT\*\shell\runas]
        ///
        ///[-HKEY_CLASSES_ROOT\Directory\shell\runas]
        ///
        ///[-HKEY_CLASSES_ROOT\dllfile\shell\runas]
        ///
        ///
        ///; To remove newer current Take Ownership context menu
        ///[-HKEY_CLASSES_ROOT\*\shell\TakeOwnership]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string removeownership {
            get {
                return ResourceManager.GetString("removeownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///; Created by: Shawn Brink
        ///; Created on: January 28th 2015
        ///; Updated on: February 16th 2018
        ///; Tutorial: https://www.tenforums.com/tutorials/3841-add-take-ownership-context-menu-windows-10-a.html
        ///
        ///
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\TakeOwnership]
        ///@=&quot;Take Ownership&quot;
        ///&quot;HasLUAShield&quot;=&quot;&quot;
        ///&quot;NoWorkingDirectory&quot;=&quot;&quot;
        ///&quot;Position&quot;=&quot;middle&quot;
        ///
        ///[HKEY_CLASSES_ROOT\*\shell\TakeOwnership\command]
        ///@=&quot;powershell -windowstyle hidden -command \&quot;Start-Process cmd -ArgumentList &apos;/c takeow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string takeownership {
            get {
                return ResourceManager.GetString("takeownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WinTimerTester {
            get {
                object obj = ResourceManager.GetObject("WinTimerTester", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
